version: "3"

services:
  flask:
    build: flask/
    
    command: ./app.py

    ports:
    - 5000:5000
        
    depends_on:
    - db
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockertest
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      

    ports:
      - 3306:3306

  
